#!/bib/bash

localBlockHeight=$(curl -s http://127.0.0.1:8545 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":0}' | jq ".result")
remoteBlockHeight=$(curl -s https://pre-alpha-us-http-geth.opside.network -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":0}' | jq ".result")
localBlockHeightNum=${localBlockHeight:3:-1}
remoteBlockHeightNum=${remoteBlockHeight:3:-1}
((localBlockHeightNum=16#$localBlockHeightNum));
((remoteBlockHeightNum=16#$remoteBlockHeightNum));
diffBlockHeight=$(expr $remoteBlockHeightNum - $localBlockHeightNum)

if [ $diffBlockHeight -gt 10 ]
  then
    isSynced=false
  else
    isSynced=true
fi

echo localHeight       =   $localBlockHeight
echo remoteHeight      =   $remoteBlockHeight
echo isSynced          =   $isSynced

