#!/bib/bash

localBlockHeightNum=${localBlockHeight:3:-1}
remoteBlockHeightNum=${remoteBlockHeight:3:-1}
((localBlockHeightNum=16#$localBlockHeightNum));
((remoteBlockHeightNum=16#$remoteBlockHeightNum));
echo "${LocalBlockHeight}$localBlockHeightNum"
echo "${RemoteBlockHeight}$remoteBlockHeightNum"
diffBlockHeight=$(expr $remoteBlockHeightNum - $localBlockHeightNum)

echo "${DiffBlockHeight}$diffBlockHeight"
if [ $diffBlockHeight -gt 10 ]
  then
    isSynced=false
  else
    isSynced=true
fi

echo localHeight       =   $localBlockHeight
echo remoteHeight      =   $remoteBlockHeight
echo isSynced          =   $isSynced

